---
- name: Services facts
  ansible.builtin.service_facts:
  tags:
    - prometheus-node-exporter
    - clean
    - facts

- name: Package clean
  ansible.builtin.package:
    name:
      - ipmitool
      - nvme-cli
      - openipmi
      - smartmontools
    state: absent
    purge: true
    update_cache: false
  tags:
    - prometheus-node-exporter
    - clean
    - package
