---
# tasks file for prometheus-node-exporter
- name: Install
  ansible.builtin.import_tasks: install.yml
- name: Configure
  ansible.builtin.import_tasks: configure.yml
- name: Clean
  ansible.builtin.import_tasks: clean.yml
  when: ansible_virtualization_role == 'guest'
